### ISSUE TITLE
python 1_optimize_cpcv.py error

### ISSUE THREAD

**Issue by SeeYaaa** [Burntt/FinRL_Crypto#2]
When i use : 
python 1_optimize_cpcv.py

i get following error:
 python 1_optimize_cpcv.py

 python 1_optimize_cpcv.py
10
TRAIN_START_DATE:  2022-02-02 04:40:00
VAL_END_DATE:  2022-04-29 23:55:00

Starting CPCV optimization with:
drl algorithm:        ppo
name_test:            model
gpu_id:               0

##### Launched hyperparameter optimization with CPCV  #####

TIMEFRAME                   5m
TRAIN SAMPLES               20000
TRIALS NO.                  50
N                           5
K test groups               2
SPLITS                      10

TRAIN SAMPLES               20000
VAL_SAMPLES                 5000
TRAIN_START_DATE            2022-02-02 04:40:00
TRAIN_END_DATE              2022-04-12 15:15:00
VAL_START_DATE              2022-04-12 15:20:00
VAL_END_DATE                2022-04-29 23:55:00

TICKER LIST                 ['BTCUSDT', 'ETHUSDT']

/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/samplers/_tpe/sampler.py:263: ExperimentalWarning: ``multivariate`` option is an experimental feature. The interface can change in the future.
  warnings.warn(
[I 2023-02-21 11:43:29,394] A new study created in memory with name: no-name-79cf0045-f7b8-4b70-a4ef-86c712939aeb

LOADING DATA FOLDER:  ./data/5m_25000

No. Train Samples: 14994

| Arguments Remove cwd: ./train_results/cwd_tests/model_CPCV_ppo_5m_50H_25k
################################################################################
ID     Step    maxR |    avgR   stdR   avgS  stdS |    expR   objC   etc.
[W 2023-02-21 11:43:29,460] Trial 0 failed because of the following error: ValueError('operands could not be broadcast together with shapes (2,) (10,) ')
Traceback (most recent call last):
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "1_optimize_cpcv.py", line 332, in obj_with_argument
    return objective(trial, name_test, model_name, cwd, res_timestamp, gpu_id)
  File "1_optimize_cpcv.py", line 269, in objective
    sharpe_bot, sharpe_eqw, drl_rets_tmp = train_and_test(trial, price_array, tech_array, train_indices,
  File "/home/sb/Lab_4/FinRL_Crypto/function_train_test.py", line 33, in train_and_test
    train_agent(price_array,
  File "/home/sb/Lab_4/FinRL_Crypto/function_train_test.py", line 72, in train_agent
    agent.train_model(model=model,
  File "/home/sb/Lab_4/FinRL_Crypto/drl_agents/elegantrl_models.py", line 86, in train_model
    train_and_evaluate(model)
  File "/home/sb/Lab_4/FinRL_Crypto/train/run.py", line 40, in train_and_evaluate
    trajectory = agent.explore_env(env, target_step)
  File "/home/sb/Lab_4/FinRL_Crypto/drl_agents/agents/AgentPPO.py", line 74, in explore_one_env
    next_s, reward, done, _ = env.step(get_a_to_e(ten_a)[0].numpy())
  File "/home/sb/Lab_4/FinRL_Crypto/environment_Alpaca.py", line 113, in step
    for index in np.where(actions < -self.minimum_qty_alpaca)[0]:
ValueError: operands could not be broadcast together with shapes (2,) (10,)
Traceback (most recent call last):
  File "1_optimize_cpcv.py", line 364, in <module>
    optimize(name_test, name_model, gpu_id)
  File "1_optimize_cpcv.py", line 345, in optimize
    study.optimize(
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/study/_optimize.py", line 177, in _optimize_sequential
    callback(study, frozen_trial)
  File "1_optimize_cpcv.py", line 98, in save_best_agent
    if study.best_trial.number != trial.number:
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/study/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/sb/anaconda3/envs/xucc/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 311, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.

**Comment by tty666** [comment]
I had the same error and the explanation was finally simple even if I got crazy for few minutes ...
they hardcoded the net dimension for optuna optimization to "10" which is the inital number of TICKERS defined into the config_main.py.
I guess you changed this list to put only 2 coins pairs ... (BTC/ETH ? uh ?) and then the table is not equal to the number of 10 hardcoded and initially defined in this list ...

Solution ? Put back the initial pairs or just adapt the hyperparameters for Optuna :
initially :
"net_dimension": trial.suggest_categorical("net_dimension", [2 ** 9, 2 ** *10*,** 2 ** 11, 2 ** 12]),
"net_dimension": trial.suggest_categorical("net_dimension", [2 ** 9, 2 ** *2*, 2 ** 11, 2 ** 12]),

**Comment by tty666** [comment]
In this :
def sample_hyperparams(trial):
    average_episode_step_min = no_candles_for_train + 0.25 * no_candles_for_train
    sampled_erl_params = {
        "learning_rate": trial.suggest_categorical("learning_rate", [3e-2, 2.3e-2, 1.5e-2, 7.5e-3, 5e-6]),
        "batch_size": trial.suggest_categorical("batch_size", [512, 1280, 2048, 3080]),
        "gamma": trial.suggest_categorical("gamma", [0.85, 0.99, 0.999]),
        "net_dimension": trial.suggest_categorical("net_dimension", [2 ** 9, 2 ** 18, 2 ** 11, 2 ** 12]),
        "target_step": trial.suggest_categorical("target_step",
                                                 [average_episode_step_min, round(1.5 * average_episode_step_min),
                                                  2 * average_episode_step_min]),
        "eval_time_gap": trial.suggest_categorical("eval_time_gap", [60]),
        "break_step": trial.suggest_categorical("break_step", [3e4, 4.5e4, 6e4])
    }
